accounts/urls.py
from django.urls import path
from accounts import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('userreg/',views.User_Registration,name='userreg'),
    path("userlogin/", views.UserLogin, name="userlogin"),
    path("userdetails",views.UserDetails,name="userdetails"),
    path('edit_user_profile/', views.edit_user_profile, name='edit_user_details'),
    # path("adminlogin/", views.OwnerLogin, name="adminlogin"),
    
    
    path('ownerreg/',views.Owner_Registration,name='ownerreg'),
    path("ownerdetails",views.OwnerDetails,name="ownerdetails"),
    path('edit_owner_profile/', views.edit_owner_profile, name='edit_owner_details'),

    path('agentreg/',views.Agent_Registration,name='agentreg'),
    path("agentdetails",views.AgentDetails,name="agentdetails"),
    path('edit_agent_profile/', views.edit_agent_profile, name='edit_agent_details'),

    path('login/',views.UserLogin, name='login'),
    path("logout",views.UserLogout,name="logout"),
    
    path('wishlist/', views.view_wishlist, name='wishlist'),
    path('wishlist/add/<int:property_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('wishlist/remove/<int:property_id>/', views.remove_from_wishlist, name='remove_from_wishlist'),

    path('subscribe/', views.create_subscription, name='create_subscription'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

uniqueproperties1/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('accounts/',include("accounts.urls")),
    path('',include("properties.urls")),
    path('admin/', admin.site.urls),
]+ static (settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
# from properties.models import property

class property_owner(models.Model):
    user_type = models.CharField(max_length=10, default='owner')
    owner = models.OneToOneField(User, on_delete=models.CASCADE)

    phone = models.CharField(max_length=100)  
    address = models.CharField(max_length=255, blank=True, null=True)
    owner_image=models.ImageField(upload_to='owner_img/',blank=True,null=True)

    def __str__(self):
        return self.owner.username
    
class Agents(models.Model):
    user_type = models.CharField(max_length=10,  default='agent')
    agent = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=100)  
    address = models.CharField(max_length=255, blank=True, null=True)
    agent_image=models.ImageField(upload_to='agent_img/',blank=True,null=True)

    def __str__(self):
        return self.agent.username
    
class UserProfile(models.Model):  
    USER_TYPE_CHOICES = [
        ('regular', 'Regular User'),
        ('owner', 'Property Owner')
    ]
    user_type = models.CharField(max_length=10, choices=USER_TYPE_CHOICES, default='regular')
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=15)  
    address = models.CharField(max_length=15,blank=True,null=True)  
    images=models.ImageField(upload_to="user_imag",blank=True,null=True)


    def __str__(self):
        return self.user.username

class Wishlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='wishlist')
    property = models.ForeignKey("properties.property", on_delete=models.CASCADE, related_name='wishlisted_by')
    added_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.property.name}"

class Subscription(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='subscriptions')
    username = models.CharField(max_length=150)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.username} - ${self.price}"

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from accounts.models import *
# from django_recaptcha.fields import ReCaptchaField

# user forms section
class UserForm1(forms.ModelForm):
    class Meta:
        model=User
        fields=["username","first_name","last_name","email","password"]
        
class UserForm2(forms.ModelForm):
    class Meta:
        model=UserProfile
        fields= ['phone','address','images']
    # captcha = ReCaptchaField()


class EditUserProfileForm1(forms.ModelForm):
    class Meta:
        model = User
        fields=["username","first_name","last_name","email",]

class EditUserProfileForm2(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields=['phone','address','images']

# owners forms section
class OwnerForm1(forms.ModelForm):
    class Meta:
        model=User
        fields=["username","first_name","last_name","email","password"]
        
class OwnerForm2(forms.ModelForm):
    class Meta:
        model=property_owner
        fields=['phone','address','owner_image']
    # captcha = ReCaptchaField()

class EditOwnerProfileForm1(forms.ModelForm):
    class Meta:
        model=User
        fields=["username","first_name","last_name","email",]

class EditOwnerProfileForm2(forms.ModelForm):
    class Meta:
        model=property_owner
        fields=['phone','address','owner_image'] 

# Agents forms section

class AgentForm1(forms.ModelForm):
    class Meta:
        model=User
        fields=["username","first_name","last_name","email","password"]
        
class AgentForm2(forms.ModelForm):
    class Meta:
        model=Agents
        fields=['user_type','phone','address','agent_image']
    # captcha = ReCaptchaField()

class EditAgentProfileForm(forms.ModelForm):
    class Meta:
        model = Agents
        fields = ['phone', 'address', 'agent_image'] 

class SubscriptionForm(forms.ModelForm):
    class Meta:
        model = Subscription
        fields = ['user', 'username', 'price']  # Include only relevant fields

    def __init__(self, *args, **kwargs):
        # Retrieve the current user from the view
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        
        # If the user is provided, set the initial values for the fields and make them non-editable
        if user:
            self.fields['user'].initial = user
            self.fields['user'].queryset = User.objects.filter(id=user.id)  # Limit queryset to the current user
            self.fields['user'].disabled = True
            
            self.fields['username'].initial = user.username
            self.fields['username'].disabled = True

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from accounts.models import UserProfile,property_owner,Wishlist
from properties.models import property
from accounts.forms import *
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponse,HttpResponseRedirect
from django.shortcuts import render, get_object_or_404,redirect
from django.contrib import messages

# Create your views here.
def User_Registration(request):
    registation=False
    if request.method=='POST':
        form1 = UserForm1(request.POST, request.FILES)
        form2 = UserForm2(request.POST, request.FILES)
        if form1.is_valid() and form2.is_valid():
            user=form1.save()
            user.set_password(user.password)
            user.save()

            profile=form2.save(commit=False)
            profile.user=user
            profile.save()
            messages.success(request, "Resistered successfully!")
            registation=True
            return redirect('login')
    else:
        form1 = UserForm1()
        form2=UserForm2()
    return render(request,"accounts/usereg.html",{"form1":form1,"form2":form2, "registation":registation})

def UserLogin(request):
    if request.method == 'POST':
        username = request.POST.get("username")
        password = request.POST.get("password")
        print(username, password)
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                messages.success(request, "Logged in  successfully!")
                return redirect("index")
            else:
                return HttpResponse("User is not active")
        else:
            return HttpResponse("Check your credentials!!")
    return render(request, "accounts/login.html")

def UserDetails(request):
    has_subscription = Subscription.objects.filter(user=request.user).exists()
    UserDetails=UserProfile.objects.get(user=request.user)
    return render(request,'accounts/userdetails.html',{'UserDetails':UserDetails,"has_subscription":has_subscription})

def edit_user_profile(request):
    user_profile = get_object_or_404(UserProfile, user=request.user)
    if request.method == 'POST':
        form1 = EditUserProfileForm1(request.POST, request.FILES, instance=request.user)
        form2 = EditUserProfileForm2(request.POST, request.FILES, instance=user_profile)
        if form1.is_valid() and form2.is_valid():
            user = form1.save(commit=False)
            user.save()

            profile = form2.save(commit=False)
            profile.user = user
            profile.save()
            return redirect('userdetails')
    else:
        form1 = EditUserProfileForm1(instance=request.user)
        form2 = EditUserProfileForm2(instance=user_profile)
    return render(request, 'accounts/edit_user_details.html', {'form1': form1, 'form2': form2 })

def UserLogout(request):
    logout(request)
    messages.success(request, "Logout successfully!")
    return redirect("login")

def Owner_Registration(request):
    registation=False
    if request.method=='POST':
        form1 = OwnerForm1(request.POST, request.FILES)
        form2 = OwnerForm2(request.POST, request.FILES)
        if form1.is_valid() and form2.is_valid():
            user=form1.save()
            user.set_password(user.password)
            user.save()

            profile=form2.save(commit=False)
            profile.owner=user
            profile.save()
            registation=True
            return redirect('login')
    else:
        form1 = OwnerForm1()
        form2=OwnerForm2()
    return render(request,"accounts/ownerreg.html",{"form1":form1,"form2":form2, "registation":registation})


def OwnerLogin(request):
    if request.method == 'POST':
        username = request.POST.get("admin_username")
        password = request.POST.get("admin_password")
        print(username, password)
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return redirect("index")
            else:
                return HttpResponse("User is not active")
        else:
            return HttpResponse("Check your credentials!")
    return render(request, "accounts/login.html")


def edit_owner_profile(request):
    # Get the profile of the currently logged-in user
    owner_profile = get_object_or_404(property_owner, owner=request.user)

    if request.method == 'POST':
        # Pass the logged-in user's instance to the form
        form1 = EditOwnerProfileForm1(request.POST, instance=request.user)
        form2 = EditOwnerProfileForm2(request.POST, request.FILES, instance=owner_profile)

        if form1.is_valid() and form2.is_valid():
            # Save form1 (User model changes)
            user = form1.save(commit=False)
            user.save()

            # Save form2 (property_owner model changes)
            profile = form2.save(commit=False)
            profile.owner = user
            profile.save()

            return redirect('ownerdetails')
    else:
        # Pass the logged-in user's instance to the form
        form1 = EditOwnerProfileForm1(instance=request.user)
        form2 = EditOwnerProfileForm2(instance=owner_profile)

    return render(request, 'accounts/edit_owner_details.html', {'form1': form1, 'form2': form2})

@login_required
def OwnerDetails(request):
    OwnerDetails=property_owner.objects.get(owner=request.user)
    OwnerProperties = property.objects.filter(owners=request.user).order_by('id')
    # OwnerProperties = property.objects.filter(owners =OwnerDetails).order_by('id')
    return render(request,'accounts/ownerdetails.html',{'OwnerDetails':OwnerDetails,'OwnerProperties':OwnerProperties})

def OwnerLogout(request):
    logout(request)
    messages.success(request, "Logout successfully!")
    return redirect("login")

# def UserDetails(request):
#     if request.user.UserProfile.user_type =='regular':
#         print(request.user.id)
#         UserDetails=UserProfile.objects.get(user=request.user)
#         return render(request,'accounts/userdetails.html',{'UserDetails':UserDetails})
#     else:
#         print("hi")
#         UserDetails=property_owner.objects.get(owner=request.user)
#         return render(request,'accounts/ownerdetails.html',{'UserDetails':UserDetails})


def Agent_Registration(request):
    registation=False
    if request.method=='POST':
        form1 = AgentForm1(request.POST, request.FILES)
        form2 = AgentForm2(request.POST, request.FILES)
        if form1.is_valid() and form2.is_valid():
            user=form1.save()
            user.set_password(user.password)
            user.save()

            profile=form2.save(commit=False)
            profile.agent=user
            profile.save()
            messages.success(request, "Resistered successfully!")
            registation=True
            return redirect('login')
    else:
        form1 = AgentForm1()
        form2=AgentForm2()
    return render(request,"accounts/usereg.html",{"form1":form1,"form2":form2, "registation":registation})

def edit_agent_profile(request):
    agent_profile = get_object_or_404(Agents, agent=request.user)
    if request.method == 'POST':
        form = EditAgentProfileForm(request.POST, request.FILES, instance=agent_profile)
        if form.is_valid():
            form.save()
            return redirect('agentdetails')
    else:
        form = EditAgentProfileForm(instance=agent_profile)
    return render(request, 'accounts/edit_agent_details.html', {'form': form})


def AgentDetails(request):
    AgentDetails=Agents.objects.get(agent =request.user)
    AgentProperties = property.objects.filter(owners = request.user).order_by('id')
    return render(request,'accounts/agentdetails.html',{'AgentDetails':AgentDetails,
                                                        'AgentProperties':AgentProperties,})


# Wishlist section

@login_required
def view_wishlist(request):
    wishlist_items = Wishlist.objects.filter(user=request.user)
    return render(request, 'accounts/wishlist.html', {'wishlist_items': wishlist_items})

@login_required
def add_to_wishlist(request, property_id):
    property_item = property.objects.get(id=property_id)
    Wishlist.objects.get_or_create(user=request.user, property=property_item)
    # return redirect('wishlist')
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

@login_required
def remove_from_wishlist(request, property_id):
    Wishlist.objects.filter(user=request.user, property_id=property_id).delete()
    # return redirect('wishlist')
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


@login_required
def create_subscription(request):
    if request.method == 'POST':
        form = SubscriptionForm(request.POST, user=request.user)
        if form.is_valid():
            form.save()
            return redirect('index')  # Redirect to a success page or another view
    else:
        form = SubscriptionForm(user=request.user)
    return render(request, 'accounts/subscription_form.html', {'form': form})

templates/accounts/agent_details_for_users.html
{% extends 'base.html' %}
{% block content %}
<p>hi</p>

{% endblock %}

templates/accounts/agentdetails.html
{% extends 'base.html' %}
{% block content %}

<div class="container mt-5">
    <div class="row">
        <div class="col-md-4">
            <!-- User Profile Image -->
            {% if AgentDetails.agent_image %}
                <img style="height: 200px; width:200px;" src="{{ AgentDetails.agent_image.url }}" alt="Profile Picture" class="img-fluid rounded-circle">
            {% else %}
                <p>No image available</p>
            {% endif %}
        </div>
        <div class="col-md-8">
            <!-- User Details -->
            <h2>{{ request.user.first_name }} {{ request.user.last_name }}</h2>
            <ul class="list-group">
                <li class="list-group-item"><strong>Email:</strong> {{ user.email }}</li>
                <li class="list-group-item"><strong>Phone:</strong> {{ AgentDetails.phone }}</li>
                <li class="list-group-item"><strong>Address:</strong> {{ AgentDetails.address }}</li>
            </ul>
            <br>
            <!-- Edit Profile and Logout Buttons -->
            <div class="d-flex">
                <a href="{% url 'logout' %}" class="btn btn-danger">Logout</a>
                <a href="{% url 'edit_agent_details' %}" class="btn btn-primary ms-3">Edit Profile</a>
            </div>
        </div>
    </div>

    <!-- Property List in Table Format -->
    <h3 class="mt-5">Owned Properties</h3>

    <!-- Add New Property Button -->
    <div class="d-flex justify-content-end mb-3">
        <a href="{% url 'addnewproperty' %}" class="btn btn-success">Add New Property</a>
    </div>

    <table class="table table-bordered mt-3">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Location</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for property in AgentProperties %}
                <tr>
                    <td>{{ property.id }}</td>
                    <td>{{ property.name }}</td>
                    <td>{{ property.address }}</td>
                    <td>
                        <!-- Edit and Delete Buttons -->
                        <a href="{% url 'edit_property' property.id %}" class="btn btn-warning btn-sm me-3">Edit</a>
                        <a href="{% url 'delete_property' property.id %}" class="btn btn-danger btn-sm ">Delete</a>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="4" class="text-center">No properties found.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

</div>

{% endblock %}

templates/accounts/agentreg.html
{% extends "base.html" %}
{% block content %}
<br>
<div class="container">
    <div class="jumbotron">
        <h1 class="mb-4">Registration Form</h1>

        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form1|crispy }}
            {{ form2|crispy }}
            <div class="text-center mt-3">
                <input type="submit" class="btn btn-success" value="Submit">
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/accounts/buying_property.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h4 class="mb-4 text-center">Property Inquiry Form</h4>
            
            <form method="post" action="{% url 'index' %}">
                {% csrf_token %}
                
                <!-- Name Field -->
                <div class="mb-3">
                    <label for="name" class="form-label">Name</label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="Enter your name" required>
                </div>

                <!-- Mobile Number Field -->
                <div class="mb-3">
                    <label for="mobile" class="form-label">Mobile Number</label>
                    <input type="tel" class="form-control" id="mobile" name="mobile" placeholder="Enter your mobile number" pattern="[0-9]{10}" required>
                </div>

                <!-- Property Name Field -->
                <div class="mb-3">
                    <label for="property_name" class="form-label">Property Name</label>
                    <input type="text" class="form-control" id="property_name" name="property_name" placeholder="Enter the property name" required>
                </div>

                <!-- Submit Button -->
                <div class="text-center">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/accounts/edit_agent_details.html
<!-- edit_user_details.html -->
 
{% extends 'base.html' %}
{% block content %}


<div class="container mt-5">
    <h2>Edit Profile</h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Save Changes</button>
    </form>
</div>
<br>

{% endblock %}

templates/accounts/edit_owner_details.html
<!-- edit_user_details.html -->
{% extends 'base.html' %}
{% block content %}


<div class="container mt-5">
    <h2>Edit Profile</h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form1.as_p }}
        {{ form2.as_p }}
        <button type="submit" class="btn btn-primary">Save Changes</button>
    </form>
</div>
<br>

{% endblock %}

templates/accounts/edit_user_details.html
<!-- edit_user_details.html -->
{% extends 'base.html' %}
{% block content %}


<div class="container mt-5">
    <h2>Edit Profile</h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form1.as_p }}
        {{ form2.as_p }}
        <button type="submit" class="btn btn-primary">Save Changes</button>
    </form>
</div>
<br>
{% endblock %}

templates/accounts/login.html
{% extends "base.html" %}
{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <!-- User Login Section -->
            <h2 class="text-center mb-4">Login</h2>
            <form action="{% url 'userlogin' %}" method="POST" class="p-4 border rounded shadow">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" class="form-control" name="username" placeholder="Enter your username" required>
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" name="password" placeholder="Enter your password" required>
                </div>
                <br>
                <div class="d-flex justify-content-between align-items-center">
                    <button type="submit" class="btn btn-primary">Login</button>
                    <div class="ml-3">
                        <a href="{% url 'userreg' %}" class="btn btn-success">Register as User</a>
                        <a href="{% url 'ownerreg' %}" class="btn btn-success">Register as Owner</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/accounts/ownerdetails.html
{% extends 'base.html' %}
{% block content %}

<div class="container mt-5">
    <div class="row">
        <div class="col-md-4">
            <!-- User Profile Image -->
            {% if OwnerDetails.owner_image %}
                <img style="height: 200px; width:200px;" src="{{ OwnerDetails.owner_image.url }}" alt="Profile Picture" class="img-fluid rounded-circle">
            {% else %}
                <p>No image available</p>
            {% endif %}
        </div>
        <div class="col-md-8">
            <!-- User Details -->
            <h2>{{ request.user.first_name }} {{ request.user.last_name }}</h2>
            <ul class="list-group">
                <li class="list-group-item"><strong>Email:</strong> {{ user.email }}</li>
                <li class="list-group-item"><strong>Phone:</strong> {{ OwnerDetails.phone }}</li>
                <li class="list-group-item"><strong>Address:</strong> {{ OwnerDetails.address }}</li>
            </ul>
            <br>
            <!-- Edit Profile and Logout Buttons -->
            <div class="d-flex">
                <a href="{% url 'logout' %}" class="btn btn-danger">Logout</a>
                <a href="{% url 'edit_owner_details' %}" class="btn btn-primary ms-3">Edit Profile</a>
            </div>
        </div>
    </div>

    <!-- Property List in Table Format -->
    <h3 class="mt-5">Owned Properties</h3>

    <!-- Add New Property Button -->
    <div class="d-flex justify-content-end mb-3">
        <a href="{% url 'addnewproperty' %}" class="btn btn-success">Add New Property</a>
    </div>

    <table class="table table-bordered mt-3">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Location</th>
                <th style="width: 22%;">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for property in OwnerProperties %}
                <tr>
                    <td>{{ property.id }}</td>
                    <td>{{ property.name }}</td>
                    <td>{{ property.address }}</td>
                    <td>
                        <!-- View Button -->
                        <a href="{% url 'property_details' property.id %}" class="btn btn-primary btn-sm me-3">View</a>
                        <!-- Edit Button -->
                        <a href="{% url 'edit_property' property.id %}" class="btn btn-warning btn-sm me-3">Edit</a>
                        <!-- Delete Button -->
                        <a href="{% url 'delete_property' property.id %}" class="btn btn-danger btn-sm">Delete</a>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="4" class="text-center">No properties found.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    

</div>

{% endblock %}

templates/accounts/ownerreg.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<link
        rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    >
<br>
<div class="container">
    <div class="jumbotron">
        <h1 class="mb-4" style="text-align: center;">Registration Form</h1 >

        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form1|crispy }}
            {{ form2|crispy }}
            <div class="text-center mt-3">
                <input type="submit" class="btn btn-success" value="Submit">
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/accounts/subscription_form.html
    <!-- Include Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            background-color: #f9f9f9;
            font-family: Arial, sans-serif;
        }

        .subscription-container {
            max-width: 600px;
            margin: 50px auto;
            padding: 20px;
            background: #fff;
            border-radius: 10px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        }

        .subscription-header {
            text-align: center;
            margin-bottom: 20px;
        }

        .subscription-header h1 {
            font-size: 24px;
            font-weight: bold;
            margin: 0;
        }

        .subscription-header p {
            font-size: 16px;
            color: #555;
        }

        .btn-submit {
            background-color: #007bff;
            color: #fff;
            border: none;
            width: 100%;
            padding: 10px;
            font-size: 16px;
            border-radius: 5px;
            cursor: pointer;
        }

        .btn-submit:hover {
            background-color: #0056b3;
        }
    </style>

    <div class="subscription-container">
        <div class="subscription-header">
            <h1>Subscribe to Our Service</h1>
            <p>Fill out the form below to activate your subscription.</p>
        </div>

        <form method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label for="id_user" class="form-label"><strong>User</strong></label>
                {{ form.user }}
            </div>

            <div class="mb-3">
                <label for="id_username" class="form-label"><strong>Username</strong></label>
                {{ form.username }}
            </div>

            <div class="mb-3">
                <label for="id_price" class="form-label"><strong>Price</strong></label>
                {{ form.price }}
            </div>

            <button type="submit" class="btn-submit">Subscribe</button>
        </form>
    </div>

    <!-- Include Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>

templates/accounts/userdetails.html
{% extends 'base.html' %}
{% block content %}

<div class="container mt-5">
    <div class="row">
        <!-- Subscription Status Indicator at the top-right -->
        <div class="col-12 d-flex justify-content-end mb-3">
            {% if has_subscription %}
                <span class="badge bg-success" style="font-size: 1.2rem; padding: 0.5rem 1rem;">Subscribed</span>
            {% else %}
                <a href="{% url 'create_subscription' %}" class="btn btn-outline-primary badge bg-success" style="font-size: 1.2rem; padding: 0.5rem 1rem;">Subscribe</a>
            {% endif %}
        </div>

        <div class="col-md-4">
            <!-- User Profile Image -->
            {% if UserDetails.images %}
                <img style="height: 200px; width:200px;" src="{{ UserDetails.images.url }}" alt="Profile Picture" class="img-fluid rounded-circle">
            {% else %}
                <p>No image</p>
            {% endif %}
        </div>
        <div class="col-md-8">
            <!-- User Details -->
            <h2>{{ request.user.first_name }} {{ request.user.last_name }}</h2>
            <ul class="list-group">
                <li class="list-group-item"><strong>Email:</strong> {{ user.email }}</li>
                <li class="list-group-item"><strong>Phone:</strong> {{ UserDetails.phone }}</li>
                <li class="list-group-item"><strong>Address:</strong> {{ UserDetails.address }}</li>
            </ul>
            <br>
             <!-- Edit Profile and Logout Buttons -->
             <div class="d-flex">
                <a href="{% url 'logout' %}" class="btn btn-danger">Logout</a>
                <a href="{% url 'edit_user_details' %}" class="btn btn-primary ms-3">Edit Profile</a>
                {% if not has_subscription %}
                    <a href="{% url 'create_subscription' %}" class="btn btn-primary ms-3">Buy Subscription</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
<br>
{% endblock %}